### ISSUE TITLE
Tracking Issue: README to Docs

### ISSUE THREAD

**Issue by stockholmux** [bottlerocket-os/bottlerocket-project-website#196]
This is a living issue to track the effort of transition content to bottlerocket.dev and pointing user-oriented documentation from the bottlerocket-os/bottlerocket README to bottlerocket.dev

_Context_: There is a lot of good information that lives on the the bottlerocket README but it lacks the ability to be versioned or localized and is a mixture of developer-oriented and user-oriented information. Consequently, it's difficult to consume. Bottlerocket.dev was introduced to gradually take the place of the readme for user-facing docs.

The goal is to replace user-facing docs on the readme with links to bottlerocket.dev, while preserving all information from the README. This is _levelling_ bottlerocket.dev. Once the content is levelled, then the readme sections can be transitioned

**API**
- [x] Level content API Content #194

**Settings**
- [x] Document settings in docs instead of readme. #203 
- [x] Remove incomplete notices on setting reference list  #308

**Other**
- [x] Document host containers before removing Settings section see #254

**Final**
- [x] Remove readme#api section and point link to bottlerocket.dev
