### ISSUE TITLE
Updates for Bottlerocket 1.15.0

### ISSUE THREAD

**Issue by stockholmux** [bottlerocket-os/bottlerocket-project-website#197]
This issue is designed to track efforts to update the docs to match the feature set for 1.15.0. 

See https://github.com/bottlerocket-os/bottlerocket/issues/3169 for current feature set and timeline

- [x] Adapt scripts for ECS variants #198 
- [x] Secure boot / chain of trust docs #217
- [x] Add versioned OpenAPI for 1.15.0 #218
- [x] Information on Report API  #220
   - [x] Add cis-k8s report API docs #268

**Comment by stockholmux** [comment]
Secure boot / chain of trust docs still has a dangling draft approval and the there was a last minute add to the reporting API (#268). Tracking these as fast-follows.

**Comment by stockholmux** [comment]
closed by #302 and #299
