### ISSUE TITLE
Document bottlerocket settings on docs

### ISSUE THREAD

**Issue by stockholmux** [bottlerocket-os/bottlerocket-project-website#203]
**Path to page with content (_do not_ include domain name):** n/a

**What content is incorrect?** There is no documentation on any of the bottlerocket settings

**What should the content say or communicate?** The bottlerocket settings should be included in the documentation

- [x] `settings.motd`
- [x] `settings.kubernetes.*`
- [x] `settings.ecs.*`
- [x] `settings.cloudformation.*` #224
- [x] `settings.autoscaling.*` #225
- [x] `settings.oci-hooks.*` #226
- [x] `settings.oci-defaults.*` #227
- [x] `settings.container-registry.*` #228
- [x] `settings.container-runtime.*` #229
- [x] `settings.updates.*` #230
- [x] `settings.network.*` #231
- [x] `settings.metrics.*` #232
- [x] `settings.ntp.*` #233
- [x] `settings.kernel.*` #234
- [x] `settings.boot.*` #235
- [x] `settings.pki.*`#236
- [x] `settings.host-containers.*` #237
- [x] `settings.aws.*`#238
- [x] `settings.dns.*` #292

Note: Some of these issues are labeled "good first issue" while non-labeled ones will likely require a great deal of work and/or skill.

**Comment by stockholmux** [comment]
🥳 Closing this now that all settings are documented.
